//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortuga_DaniilArtyukhov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFood
    {
        public int ID { get; set; }
        public int IDOrder { get; set; }
        public int IDFood { get; set; }
        public byte Count { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Order Order { get; set; }
    }
}
